version: "3"

services:
  db:
    image: postgres:10-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./data/postgres:/data
    ports:
      - "${DB_PORT:-5001}:5432"

  redis:
    image: redis:5
    restart: always
    volumes:
      - ./data/redis:/data
    ports:
      - "${REDIS_PORT:-5002}:6379"

  app:
    build:
      context: .
    ports:
      - "${WEB_PORT:-8000}:${WEB_PORT:-8000}"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:${WEB_PORT:-8000}"
    depends_on:
      - db
      - redis
